PGPassword=""
JWTSecret=""
S3AccessKey=""
S3SecretKey=""
S3Host=""
SlackWebhook=""
DiscordToken=""
DiscordPublicPostChannel=""
DiscordLinkBookmarkChannel=""
TimelapseWorkers=""
TimelapseWorkerAccessKey=""
